services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: tasktrix-api
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DATABASE_URL=jdbc:postgresql://postgres:5432/trix
      - DATABASE_USERNAME=trix
      - DATABASE_PASSWORD=trixsecret
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=404E635266556A586E3272357538782F413F4428472B4B6250645367566B597033733676397924423F4528482B4D6251655468576D5A7134743777217A25432A462D4A614E645267556B58703273357638792F423F4528472B4B6250655368566D5971347436773979244326462948404D635166546A576E5A7234753778214125442A472D4A614E645267556B58703273357638792F423F4528482B4D6251655368566D597134743777217A25432646294A404E635266556A586E3272357538782F423F4528472B4B6250655368566D597134743777217A25
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,http://localhost:4200
      - JAVA_OPTS=-Xmx512m -Xms256m
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - trix_network
    volumes:
      - app-logs:/app/logs
    restart: unless-stopped

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: trix-postgres
    environment:
      - POSTGRES_DB=trix
      - POSTGRES_USER=trix
      - POSTGRES_PASSWORD=trixsecret
      - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    networks:
      - trix_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U trix -d trix"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: trix-redis
    command: redis-server --appendonly yes --requirepass redissecret
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf:ro
    networks:
      - trix_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

networks:
  trix_network:
    driver: bridge

volumes:
  postgres-data:
    driver: local
  redis-data:
    driver: local
  app-logs:
    driver: local